<div class="mt-xl-5 text-center">
    <h1 class="mt-5 text-primary">Cart</h1>
</div>
<div class="container mt-xl-5">
    <div class="row mt-5">
        <div class="col">
            <div class="product-content-right">
                <form method="GET" action="#">
                    <table cellspacing="0" class="table table-hover">
                        <thead class="bg-dark text-light">
                            <tr>
                                <th class="product-thumbnail">Product Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-subtotal">Total</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        print_r($cart);
                        foreach ($cart as $product) {
                            echo '<tr class="cart_item">
                                    <td class="product-thumbnail">
                                        <a href="#"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="/assets/img/'.$product['image'].'"></a>
                                    </td>
                                    <td class="product-name">
                                        <a href="#">'.$product['name'].'</a>
                                    </td>
                                    <td class="product-price">
                                        <span class="amount">$'.$product['price'].'</span>
                                    </td>
                                    <td class="product-quantity">
                                        <div class="quantity buttons_added">
                                            <input type="number" size="4" class="input-text qty text w-25" name="updateQty" value="'.$product['quantity'].'" min="0" step="1"><br>
                                        </div>
                                    </td>
                                    <td class="product-subtotal">
                                        <span class="amount">111</span>
                                    </td>
                                    <td class="product-remove">
                                        <a title="Remove this item" class="remove" href="?action=removeFromCart&remPrId='.$product['id'].'">X</a>
                                    </td>
                                </tr>';
                        }
                        ?>
                        
                        </tbody>
                    </table>
                    <a href="./checkout.php" class="btn btn-primary">Checkout</a>
                </form>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="cart_totals">
                <h2>Cart Totals</h2>
                <table cellspacing="0">
                    <tbody>
                        <tr class="cart-subtotal">
                            <th>Cart Subtotal</th>
                            <td><span class="amount">$<?php echo 100; ?></span></td>
                        </tr>

                        <tr class="shipping">
                            <th>Shipping and Handling</th>
                            <td>Free Shipping</td>
                        </tr>

                        <tr class="order-total">
                            <th>Order Total</th>
                            <td><strong><span class="amount">$<?php echo 200; ?></span></strong> </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>