
<main>
  <div class="album py-5 bg-light mt-xl-5">
      <div class="container overflow-hidden">
        <form class="row row-cols-lg-auto align-items-center mt-0 mb-3">
            <div class="col-lg-6 col-12">
              <label class="visually-hidden" for="inlineFormInputGroupUsername">Search</label>
              <div class="input-group">
                <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Product, SKU, Category">
              </div>
            </div>
          
            <div class="col-lg-3 col-12">
              <label class="visually-hidden" for="inlineFormSelectPref">Sort By</label>
              <select class="form-select" id="inlineFormSelectPref">
                <option selected></option>
                <option value="">Price:low to high</option>
                <option value="2">Price:high to low</option>
                <option value="3">Recently Added</option>
              </select>
            </div>
          
            <div class="col-lg-3 col-12">
              <button type="submit" class="btn btn-primary w-100">Search</button>
            </div>
          </form>
      </div>
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <?php
        foreach ($products as $product) {
            echo ' <div class="col">
                  <div class="card shadow-sm">
                    <img src="/assets/img/'.$product->product_image.'" class="bd-placeholder-img card-img-top" height="400" src=""></img>

                    <div class="card-body">
                        <h5>'.$product->product_name.'</h5>
                      <div class="d-flex justify-content-between align-items-center">
                        <p><strong>$'.$product->list_price.'</strong>&nbsp;<del><small class="link-danger">$'.$product->price.'</small></del></p>
                        
                      </div>
                      <a href="http://localhost:8080/index/addToCart/'.$product->id.'" class="btn btn-primary">Add To Cart</a>
                    </div>
                  </div>
                </div>';
        }
        ?>
      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">&copy; CEDCOSS Technologies</p>
  </div>
</footer>
