<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store</title>
    <link rel="stylesheet" href="/assets/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <style>
        .login-icon{
            font-size: 80px;
            color: #0B5ED7;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <?php echo $this->getContent(); ?>
</div>
<script src="/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>